### ISSUE TITLE
Annotating Vocals into MIDI

### ISSUE THREAD

**Issue by SutirthaChakraborty** [interactiveaudiolab/penn#13]
Can we export vocals into MIDI? Such as [Omnizart Vocals](https://github.com/Music-and-Culture-Technology-Lab/omnizart/tree/master/omnizart/vocal) ?

**Comment by maxrmorrison** [comment]
I do not currently have a utility for converting to MIDI. However, if you (or anyone) felt like making a `penn.convert.frequency_to_midi` function, I'd be interested in that pull request!

**Comment by maxrmorrison** [comment]
Added in version 0.0.14!
