### ISSUE TITLE
CLI uses --files not --audio_files (as in README)

### ISSUE THREAD

**Issue by turian** [interactiveaudiolab/penn#14]
Nice work, I just read it this morning.

The CLI uses --files, whereas the docs say --audio_files.

(p.s. I'm curious if you have the results tables with for PTDB and MDB-STEM-SYNTH individually? Table II seems to indicate that the scores are mixed.)

**Comment by maxrmorrison** [comment]
Thanks for catching that typo--fixed!

See Figure 3 for individual (and cross-domain) results
