### ISSUE TITLE
Typo In Readme Section

### ISSUE THREAD

**Issue by newpolygons** [interactiveaudiolab/penn#17]
![image](https://github.com/interactiveaudiolab/penn/assets/30321729/239ab9de-8d1d-40e6-ae6c-218b50fe79dc)

There is an issue in this section of the readme. The readme states to use "penn.plot.thresholds" the proper name right not is "penn.plot.threshold"

**Comment by maxrmorrison** [comment]
Thanks for catching that. Fixed!
