### ISSUE TITLE
Data augmentation

### ISSUE THREAD

**Issue by egaznep** [interactiveaudiolab/penn#20]
Hi, first of all great work, thanks for open-sourcing it!

I noticed that the extractor performs suboptimally with silent audio files, possibly yielding `NaN`s. It might be due to the training dataset solely consisting of clean speech signals. I wanted to ask if there has been a reason why no data augmentation has been done, e.g., as in https://ieeexplore.ieee.org/abstract/document/10447962?

**Comment by maxrmorrison** [comment]
I think NaN isn't unreasonable for a completely silent audio file; there is no pitch in the audio. If you change the decoder to argmax, you'll get maximal entropy noise instead. If you change it to Viterbi, it will probably be monotone. How to handle silence is a decoding choice. The default model was trained on fairly noisy speech (laryngograph recordings) as well as music. Certainly, more good data or good data augmentation could further improve the model.
